//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Classrooms = new HashSet<Classroom>();
        }

        public int building_id { get; set; }

        [DisplayName("Building Prefix")]
        [StringLength(10)]
        [Required(ErrorMessage = "A Building Prefix is required")]
        [Remote("IsBuildingTaken", "Buildings", AdditionalFields = "campusPrefix")]
        public string buildingPrefix { get; set; }

        [DisplayName("Campus Prefix")]
        [StringLength(10)]
        [Required(ErrorMessage = "A Campus Prefix is required")]
        public string campusPrefix { get; set; }

        [DisplayName("Name")]
        [StringLength(100)]
        [Required(ErrorMessage = "A Building Name is required")]
        public string buildingName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classroom> Classrooms { get; set; }
    }
}
