//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classroom()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int classroom_id { get; set; }
        public int building_id { get; set; }
        public string buildingPrefix { get; set; }
        public string roomNumber { get; set; }
        public int classroomCapacity { get; set; }
        public int computers { get; set; }
        public System.TimeSpan availableFromTime { get; set; }
        public System.TimeSpan availableToTime { get; set; }
        public string active { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
