//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int course_id { get; set; }

        [DisplayName("Program")]
        public int program_id { get; set; }
        public string programPrefix { get; set; }

        [DisplayName("Prefix")]
        [StringLength(10)]
        [Required(ErrorMessage = "Course prefix is required")]
        [Remote("IsCourseTaken", "Courses", AdditionalFields = "program_id,courseNumber")]
        public string coursePrefix { get; set; }

        [DisplayName("Course Number")]
        [StringLength(10)]
        [Required(ErrorMessage = "Course number is required")]
        public string courseNumber { get; set; }

        [DisplayName("Name")]
        [StringLength(100)]
        [Required(ErrorMessage = "Course name is required")]
        public string courseName { get; set; }

        [DisplayName("Default Credits")]
        public Nullable<decimal> defaultCredits { get; set; }

        [DisplayName("Active")]
        public string active { get; set; }
    
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
