//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorDepartment
    {
        public int instructorDepartment_id { get; set; }
        public int department_id { get; set; }
        public int instructor_id { get; set; }
        public string departmentPrefix { get; set; }
        public string instructorWNumber { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
