//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.InstructorPrograms = new HashSet<InstructorProgram>();
            this.InstructorReleases = new HashSet<InstructorRelease>();
            this.Sections = new HashSet<Section>();
        }
    
        public int instructor_id { get; set; }

        [DisplayName("W Number")]
        [StringLength(9)]
        [Required(ErrorMessage = "Instructor wnumber is required")]
        public string instructorWNumber { get; set; }

        [DisplayName("First Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Instructor first name is required")]
        public string instructorFirstName { get; set; }

        [DisplayName("Last Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Instructor last name is required")]
        public string instructorLastName { get; set; }

        [DisplayName("Hours Required")]
        public Nullable<decimal> hoursRequired { get; set; }

        [DisplayName("Active")]
        public string active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorProgram> InstructorPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorRelease> InstructorReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
