//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class InstructorRelease
    {
        public int instructorRelease_id { get; set; }

        [DisplayName("Instructor")]
        public int instructor_id { get; set; }

        [DisplayName("Semester")]
        public int semester_id { get; set; }
        public string instructorWNumber { get; set; }
        public string semesterType { get; set; }
        public int semesterYear { get; set; }

        [DisplayName("Description")]
        [StringLength(255)]
        [Required(ErrorMessage = "Description is required")]
        public string releaseDescription { get; set; }

        [DisplayName("Total Release Hours")]
        public Nullable<decimal> totalReleaseHours { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
