//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.Courses = new HashSet<Course>();
            this.InstructorPrograms = new HashSet<InstructorProgram>();
        }
    
        public int program_id { get; set; }
        [Required(ErrorMessage = "Program prefix is required")]
        [Remote("IsProgramTaken", "Programs", AdditionalFields = "programName")]
        public string programPrefix { get; set; }
        [Required(ErrorMessage = "Program name is required")]
        public string programName { get; set; }
        public decimal maxCreditsAllowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorProgram> InstructorPrograms { get; set; }
    }
}
