//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Section
    {
        // These are also database constraints if you want to add or modify these then you need to make changes to the
        // Database as well
        public static Dictionary<String, String> CourseTypes = new Dictionary<string, string> { { "Traditional", "TRAD" }, { "Online", "ONL" }, { "Hybrid", "HYB" } };
        public static Dictionary<String, String> BlockTypes = new Dictionary<string, string> { { "Semester", "S" }, { "First Block", "FB" }, { "Second Block", "SB" } };

        public int section_id { get; set; }
        public int course_id { get; set; }
        public Nullable<int> classroom_id { get; set; }
        public Nullable<int> instructor_id { get; set; }
        public Nullable<int> semester_id { get; set; }
        [Required(ErrorMessage = "Course prefix is required")]
        public string coursePrefix { get; set; }
        [Required(ErrorMessage = "Course number is required")]
        public string courseNumber { get; set; }
        [Required(ErrorMessage = "Building prefix is required")]
        public string buildingPrefix { get; set; }
        [Required(ErrorMessage = "Room number is required")]
        public string roomNumber { get; set; }
        [Required(ErrorMessage = "Instructor wnumber is required")]
        public string instructorWNumber { get; set; }
        [Required(ErrorMessage = "Program prefix is required")]
        public string semesterType { get; set; }
        public Nullable<int> semesterYear { get; set; }
        [Required(ErrorMessage = "CRN is required")]
        public string crn { get; set; }
        [Required(ErrorMessage = "Days taught is required")]
        public string daysTaught { get; set; }
        public System.TimeSpan courseStartTime { get; set; }
        public System.TimeSpan courseEndTime { get; set; }
        public string block { get; set; }
        public string courseType { get; set; }
        public string pay { get; set; }
        public int sectionCapacity { get; set; }
        public Nullable<decimal> creditLoad { get; set; }
        public Nullable<decimal> creditOverload { get; set; }
        public string comments { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
